ARG FLUENTD_VERSION=v1.17.0-debian-1.0
FROM fluent/fluentd:${FLUENTD_VERSION}
USER root
ARG PLUGIN_ELASTICSEARCH_VERSION=5.4.3
RUN gem install fluent-plugin-elasticsearch --no-document -v $PLUGIN_ELASTICSEARCH_VERSION
USER fluent
